version: '3.7'

services:
  node-ts-otimizado:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ts-tdd-node-boilerplate
    volumes:
      - ./src:/app/src
    command: yarn start
